end CDtest

diff --git a/linuxStudy/n3--shell/CDtest b/linuxStudy/n3--shell/CDtest
--- a/linuxStudy/n3--shell/CDtest
+++ b/linuxStudy/n3--shell/CDtest
@@ -1,5 +1,6 @@
 #!/bin/bash
-
+#set -e
+#set -x
 #balabala
 
 
@@ -8,13 +9,13 @@ menu_choice=""
 current_cd=""
 title_file="title.cdb"
 tracks_file="tracks.cdb"
-tmp_file=/tmp/cdb.$$
-trap "rm -f $tmp_file" EXIT
+tmp_file="tmpCdb.$$"
+trap 'rm -f $tmp_file' EXIT
 
 #function
 get_return(){
     echo -e "Press return \c"
-    read x
+    read  -r x
     return 0
 }
 
@@ -23,7 +24,7 @@ get_confirm()
     echo -e "Are you sure? \c"
     while true
     do
-        read x
+        read -r x
         case "$x" in
             y | yes | Y | Yes | YES)
                 return 0;;
@@ -41,7 +42,7 @@ set_menu_choice(){
     echo "Options :-"
     echo
     echo "  a) Add new CD"
-    echo "  b) Find CD"
+    echo "  f) Find CD"
     echo "  c) Count the CDs and tracks in the catalog"
     if [ "$cdcatnum" != "" ]
     then
@@ -52,18 +53,18 @@ set_menu_choice(){
     echo "  q) Quit"
     echo 
     echo -e "Please enter choice then press return \c"
-    read menu_choice
+    read -r menu_choice
     return    
 }
 
 
 insert_title(){
-    echo $* >> $title_file
+    echo "$@" >> $title_file
     return
 }
 
 insert_track(){
-    echo $* >> $tracks_file
+    echo "$@" >> $tracks_file
     return
 }
 
@@ -75,7 +76,7 @@ add_record_tracks(){
     while [ "$cdtitle" != "q" ]
     do
         echo -e "Track $cdtrack, track title? \c"
-        read tmp
+        read -r tmp
         # don't include ,
         cdtitle=${tmp%%,*}   #enter  title,abcd, cdtitle= title
         if [ "$tmp" != "$cdtitle" ]
@@ -85,9 +86,9 @@ add_record_tracks(){
         fi
 
         # is null?
-        if [ -n $cdtitle ] ;then
+        if [ -n "$cdtitle" ] ;then
             if [ "$cdtitle" != "q" ]; then
-                insert_track $cdcatnum, $cdtrack, $cdtitle
+                insert_track "$cdcatnum", "$cdtrack", "$cdtitle"
             fi
         else
             cdtrack=$((cdtrack-1))
@@ -99,26 +100,26 @@ add_record_tracks(){
 add_records(){ 
     # Prompt for the  init information
     echo -e "Enter catalog name \c"
-    read tmp
+    read -r tmp
     cdcatnum=${tmp%%,*}
     
     echo -e "Enter title \c"
-    read tmp
+    read -r tmp
     cdtitle=${tmp%%,*}
     
     echo -e "Enter type \c"
-    read tmp
+    read -r tmp
     cdtype=${tmp%%,*}
 
     echo -e "Enter artist/composer \c"
-    read tmp
+    read -r tmp
     cdac=${tmp%%,*}
 
     echo About to add new entry
     echo "$cdcatnum $cdtitle $cdtype $cdac"
     
     if get_confirm ; then
-        insert_title $cdcatnum,$cdtitle,$cdtype,$cdac
+        insert_title "$cdcatnum","$cdtitle","$cdtype","$cdac"
         add_record_tracks
     else
         remove_records
@@ -137,15 +138,15 @@ find_cd(){
     
     cdcatnum=""
     echo -e "Enter a string to search for in the CD titles \c"
-    read searchstr
+    read -r searchstr
 
     if [ "$searchstr" = "" ];then
         return 0
     fi
 
-    grep "$searchstr" $title_file > $temp_file
+    grep "$searchstr" $title_file > $tmp_file
     
-    set $(wc -l $temp_file )
+    set $(wc -l $tmp_file )
     linesfound=$1
 
     case $linesfound in
@@ -155,17 +156,17 @@ find_cd(){
     1)  ;;
     2)  echo "Sorry, not unique."
         echo "Found the following"
-        cat $temp_file
+        cat $tmp_file
         get_return
         return 0
     esac
     
     IFS=","
-    read cdcatnum cdtitle cdtype cdac < $temp_file
+    read -r cdcatnum cdtitle cdtype cdac < $tmp_file
     IFS=" "
 
     if [ -z "$cdcatnum" ];then
-        echo "Sorry, could not extract catalog field from $temp_file"
+        echo "Sorry, could not extract catalog field from $tmp_file"
         get_return
         return 0
     fi
@@ -180,7 +181,7 @@ find_cd(){
 
     if [ "$asklist" = "y" ];then
         echo -e "View tracks for this CD? \c"
-        read x
+        read -r x
         if [ "$x" = "y" ]; then
             echo 
             list_tracks
@@ -203,8 +204,8 @@ update_cd() {
         echo
         echo "This will re-enter the tracks for $cdtitle"
         get_confirm && {
-            grep -v "^${cdcatnum}," $tracks_file > $temp_file
-            mv $temp_file $tracks_file
+            grep -v "^${cdcatnum}," $tracks_file > $tmp_file
+            mv $tmp_file $tracks_file
             echo
             add_record_tracks
         }
@@ -214,10 +215,10 @@ update_cd() {
 
 
 count_cds(){ 
-    set ${wc -l $title_file}
+    set $(wc -l $title_file)
     num_titles=$1
 
-    set ${wc -l $tracks_file}
+    set $(wc -l $tracks_file)
     num_tracks=$1
     
     echo found $num_titles CDs, with a total of $num_tracks tracks
@@ -234,10 +235,10 @@ remove_records(){
     if [ -n "$cdcatnum" ];then
         echo "You are about to delete $cdtitle"
         get_confirm && {
-            grep -v "^${cdcatnum}," $title_file > $temp_file
-            mv $temp_file $title_file
-            grep -v "^${cdcatnum}," $tracks_file > $temp_file
-            mv $temp_file $tracks_file
+            grep -v "^${cdcatnum}," $title_file > $tmp_file
+            mv $tmp_file $title_file
+            grep -v "^${cdcatnum}," $tracks_file > $tmp_file
+            mv $tmp_file $tracks_file
             cdcatnum=""
             echo Entry removed
         }
@@ -251,15 +252,15 @@ list_tracks(){
         echo no CD selected yet
         return
     else
-        grep "^${cdcatnum}," $tracks_file > $temp_file
-        num_tracks=${wc -l $temp_file}
+        grep "^${cdcatnum}," $tracks_file > $tmp_file
+        num_tracks=$(wc -l "$tmp_file")
         if [ "$num_tracks" = "0" ];then
             echo no tracks found for $cdtitle
         else {
             echo
             echo "$cdtitle :-"
             echo
-            cut -f 2- -d , $temp_file
+            cut -f 2- -d , $tmp_file
             echo
         }  | ${PAGER:-more}     
         fi
@@ -267,6 +268,62 @@ list_tracks(){
     get_return
     return
 }
+
+rm -f $tmp_file
+if [ ! -f $title_file ];then
+    touch $title_file
+fi
+
+if [ ! -f $tracks_file ];then
+    touch $tracks_file
+fi
+
+#Now the application proper
+
+clear
+echo
+echo
+echo "Mini CD manager"
+sleep 1
+
+
+quit=n
+while [ "$quit" != "y" ];
+do
+    set_menu_choice
+    case "$menu_choice" in
+        a) add_records;;
+        r) remove_records;;
+        f) find_cd y;;
+        u) update_cd;;
+        c) count_cds;;
+        l) list_tracks;;
+        b) echo
+           more $title_file
+           echo
+           get_return;;
+        q | Q) quit=y;;
+        *) echo "Sorry, choice not recognized";;
+    esac
+done
+
+#tidy up and leave
+
+rm -f $tmp_file
+echo "Finished"
+exit 0
+
+
+
+
+
+
+
+
+
+
+
+
 
 
 
